-- see https://stevedonovan.github.io/ldoc/manual/doc.md.html#Fields_allowed_in__config_ld_ for config options

project = 'Nvim Config'
title = 'Nvim Config Documentation'
description = 'My nvim config for a manjaro linux wsl2 instalation.'

all=true

file = { '../lua/', '../init.lua' }
dir = './'

-- custom_tags = { { 'dependencies', title = 'Dependencies' },
--     { 'sideEffects', title = 'Side Effects' } }
